services:
  ros-dev:
    image: rishikesavanramesh/ros-one-day # change this to your docker image
    #build: .
    volumes:
      - ../../.:/workspace/.
      - /tmp/.X11-unix:/tmp/.X11-unix # Expose X11 socket
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/developer/.Xauthority # Mount Xauthority file
    environment:
      - SSH_KEY=$SSH_KEY
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/developer/.Xauthority # Set Xauthority file path
    command: sleep infinity
    user: developer
