services:
  ros-dev:
    # image: rishikesavanramesh/ros-oneday # change this to your docker image
    build: .
    volumes:
      - ../../.:/home/developer/my_ros_ws/.
      - /tmp/.X11-unix:/tmp/.X11-unix # Expose X11 socketS
    environment:
      - SSH_KEY=$SSH_KEY
      - DISPLAY=:45
    command: sleep infinity
    user: developer
