# gz topic published by the JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model" # In future, this will be gz.msgs.Model
  direction: GZ_TO_ROS

  
# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/onbot/joint/Joint_1/cmd_pos"
  gz_topic_name: "model/onbot/joint/Joint_1/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ
  
# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/onbot/joint/Joint_2/cmd_pos"
  gz_topic_name: "model/onbot/joint/Joint_2/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ
  
# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/onbot/joint/Joint_3/cmd_pos"
  gz_topic_name: "model/onbot/joint/Joint_3/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ
  
# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/onbot/joint/Joint_4/cmd_pos"
  gz_topic_name: "model/onbot/joint/Joint_4/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ
  
# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/onbot/joint/Joint_5/cmd_pos"
  gz_topic_name: "model/onbot/joint/Joint_5/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ
  
# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/onbot/joint/Joint_6/cmd_pos"
  gz_topic_name: "model/onbot/joint/Joint_6/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ
